### ISSUE TITLE
ValueError: number of input channels does not match corresponding dimension of filter

### ISSUE THREAD

**Issue by helxsz** [ndrplz/surround_vehicles_awareness#2]
when running the main.py to build the model based on Resnet50, the following code is shown below

input_crop = Input(shape=(3, 224, 224))

# extract feature from image crop
resnet = ResNet50(include_top=False, weights='imagenet')
for layer in resnet.layers:  # set resnet as non-trainable
    layer.trainable = False

crop_encoded = resnet(input_crop)  
However, I got an error

'ValueError: number of input channels does not match corresponding dimension of filter, 224 != 3'
how can I fix it?

**Comment by ndrplz** [comment]
@helxsz Looks like image channels are transposed. Are you sure to use CHW dimension convention (aka channels first)?

**Comment by helxsz** [comment]
@ndrplz thanks, you just remind me of that, I am using tensorflow instead of Theano

**Comment by helxsz** [comment]
```
    img_rows, img_cols = 224,224
    if K.image_data_format() == "channels_first":
        input_shape = (3, img_rows, img_cols)
    else:
        input_shape = (img_rows, img_cols, 3)

    input_crop = Input(shape=input_shape)
```

this is my fix to the problem above, however because I am using tensorflow, so I am running the main.py with an error

`ValueError: Cannot feed value of shape (1, 1, 512, 256) for Tensor u'Placeholder_80:0', which has shape '(1, 1, 256, 512)'`

 since the SDPN model is based on theano.

do you provide any trained model based on tensorflow or training code ?

**Comment by ndrplz** [comment]
@helxsz Are you sure that this new issue you encounter is due to the backend? For the error stack you shared here it looks like H and W are reversed.

**Comment by helxsz** [comment]
Yes, the H and W dimension are swapped, why is that ?

**Comment by jhtao1860** [comment]
@helxsz @ndrplz  I have met the both issues, 
for the first one, i change "input_crop = Input(shape=(3, 224, 224))" to "input_crop = Input(shape=(224,224,3))" 
but for the second one, I have no idea:
"ValueError: Cannot feed value of shape (1, 1, 512, 128) for Tensor u'Placeholder_78:0', which has shape '(1, 1, 128, 512)'"
how to swap H and W?

**Comment by ndrplz** [comment]
@helxsz @jhtao1860 Did you try if in Theano runs fine? All these creepy dimension issues are likely to be related to the underlying TensorFlow backend.

**Comment by jhtao1860** [comment]
@ndrplz thank you！ Do you now how to run it in Theano？

**Comment by jhtao1860** [comment]
after install keras，should change ～/.keras/keras,jason to the foloowing:

{
    "image_dim_ordering":"th",
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "image_data_format": "channels_last", 
    "backend": "theano"
}

**Comment by ndrplz** [comment]
@jhtao1860 Yes that should work, **but** please change "channels_last" to "channels_first".

Let me know how it goes!

**Comment by jhtao1860** [comment]
@ndrplz   after changing ～/.keras/keras， by default(NOT change code)， the code can work。 If error occured,like “3 ！= 244” ， then need change "channels_last" to "channels_first"

**Comment by wedoso** [comment]
@ndrplz it works!

**Comment by radiumray** [comment]
@wedoso hi, do you mind share your tensorflow code about this project, which is works?

**Comment by wedoso** [comment]
@radiumray wow! My comment was 6 months ago. I almost forgot what we were discussing. But it seems the issue of the input format. If you meet the similar issue, you may try to modify the format from channel last to channel first or from channel last to channel first. You can just simply configure it through Keras API.

**Comment by AndreV84** [comment]
when I edit main.py substituting 244,244,3 to 3,244,244 it will throw an error of another nature. However when I run once keras and it create file ~/keras/keras.json ans I substitute 'last' to 'first' in the json file it will throw the following on execution:
`2019-02-21 16:01:14.142241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-02-21 16:01:14.142824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-21 16:01:14.142831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-02-21 16:01:14.142834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-02-21 16:01:14.142981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11013 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:04:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    model = SDPN(summary=True)
  File "/home/nvidia/surround_vehicles_awareness/model.py", line 25, in SDPN
    resnet = ResNet50(include_top=False, weights='imagenet')
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/applications/__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/applications/resnet50.py", line 11, in ResNet50
    return resnet50.ResNet50(*args, **kwargs)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras_applications/resnet50.py", line 231, in ResNet50
    x = layers.BatchNormalization(axis=bn_axis, name='bn_conv1')(x)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/layers/normalization.py", line 206, in call
    training=training)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3123, in in_train_phase
    x = switch(training, x, alt)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3058, in switch
    else_expression_fn)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2108, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1941, in BuildCondBranch
    original_result = fn()
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/layers/normalization.py", line 167, in normalize_inference
    epsilon=self.epsilon)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1908, in batch_normalization
    mean = tf.reshape(mean, (-1))
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 0 for 'bn_conv1/cond/Reshape_4' (op: 'Reshape') with input shapes: [1,64,1,1], [].
`

**Comment by AndreV84** [comment]
with explicit content of the keras.json in h'ome directory as below it returns error:
`{
"image_dim_ordering":"th",
"epsilon": 1e-07,
"floatx": "float32",
"image_data_format": "channels_last",
"backend": "theano"
}`
`Using Theano backend.
/home/nvidia/env2/local/lib/python2.7/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '
/home/nvidia/env2/local/lib/python2.7/site-packages/keras/utils/conv_utils.py:82: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.copy(kernel[slices])
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    model = SDPN(summary=True)
  File "/home/nvidia/surround_vehicles_awareness/model.py", line 30, in SDPN
    crop_encoded = Reshape(target_shape=(2048,))(crop_encoded)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 474, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/layers/core.py", line 398, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/layers/core.py", line 386, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: total size of new array must be unchanged
`
But now I know how to switch backends!

**Comment by KarthikMgk** [comment]
Ok, If my inputs are single channel, Should I still pass in 3 for no.of channels? Its weird that network works only if i pass in 3 in my input_tensor shape though my real inputs are of 1 channel

**Comment by ndrplz** [comment]
@KarthikMgk Well I would not say it's weird; if the number of channels of your input do not match the number of channels the network architecture expects, the weights' shape won't match. It's like trying to perform matrix multiplication between matrices with random shapes.

To get a 3-channel input in your case, I would simply stack three copies of your grayscale input on channel axis.

**Comment by KarthikMgk** [comment]
@ndrplz  Yes, I understand. Instead of stacking three copies, I just passed in the original 3 channel RGB input to the network to experiment whether the problem is due to channels or not. Turns out, Channels are not the problem as the same error at the same step popped out.

I also tried to pass in `(input_tensor = inception_model.input)` instead of passing `input_shape = Input(shape=(img_rows, img_cols, 3))` which didnt help either

**Comment by KarthikMgk** [comment]
@ndrplz Thanks for that helpful tip! I'm gonna try that out
Edit: It worked!!! If you can shed some light on how different it is in the models perspective that it views this 3-channel stacked grey image compared to single channel grey image, I would commit this beautiful idea/hack into my memory

**Comment by omf2333** [comment]
> with explicit content of the keras.json in h'ome directory as below it returns error:
> `{ "image_dim_ordering":"th", "epsilon": 1e-07, "floatx": "float32", "image_data_format": "channels_last", "backend": "theano" }`
> `Using Theano backend. /home/nvidia/env2/local/lib/python2.7/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)`has been changed since Keras 2.2.0. warnings.warn('The output shape of`ResNet50(include_top=False)`' /home/nvidia/env2/local/lib/python2.7/site-packages/keras/utils/conv_utils.py:82: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use`arr[tuple(seq)]`instead of`arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result. return np.copy(kernel[slices]) Traceback (most recent call last): File "main.py", line 14, in <module> model = SDPN(summary=True) File "/home/nvidia/surround_vehicles_awareness/model.py", line 30, in SDPN crop_encoded = Reshape(target_shape=(2048,))(crop_encoded) File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 474, in __call__ output_shape = self.compute_output_shape(input_shape) File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/layers/core.py", line 398, in compute_output_shape input_shape[1:], self.target_shape) File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/layers/core.py", line 386, in _fix_unknown_dimension raise ValueError(msg) ValueError: total size of new array must be unchanged `
> But now I know how to switch backends!


I encountered the exact same situation after switch keras backends. And how you fix it? thx

**Comment by Omfff** [comment]
@AndreV84 I encountered the exact same situation after switch keras backends. And how you fix it? thx
