### ISSUE TITLE
any clue? versions are not exactly the same,

### ISSUE THREAD

**Issue by AndreV84** [ndrplz/surround_vehicles_awareness#9]
/local/lib/python2.7/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    model = SDPN(summary=True)
  File "/home/nvidia/surround_vehicles_awareness/model.py", line 29, in SDPN
    crop_encoded = resnet(input_crop)  # shape of `crop_encoded` is 2018x1x1
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/engine/network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/engine/network.py", line 721, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 171, in call
    dilation_rate=self.dilation_rate)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3650, in conv2d
    data_format=tf_data_format)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 850, in convolution
    data_format=data_format)
  File "/home/nvidia/env2/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 937, in __init__
    filter_shape[num_spatial_dims]))
ValueError: number of input channels does not match corresponding dimension of filter, 224 != 3

**Comment by AndreV84** [comment]
dia/env2/local/lib/python2.7/site-packages/keras_applications/resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
94658560/94653016 [==============================] - 10s 0us/step
94666752/94653016 [==============================] - 10s 0us/step

**Comment by ndrplz** [comment]
> ValueError: number of input channels does not match corresponding dimension of filter, 224 != 3`

Looks like there's some dimension issue in you input, are keeping the right channel convention? See #2

**Comment by AndreV84** [comment]
I was just to run the file using the default sample data, as demo. I did not do any customization, but configured the infrastructure and attempted executing the code. It should load by default some sample data and default model and output some video. Shouldn't it?
Thank you for sharing the url
